[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "out"

[functions]
  directory = "../backend/functions"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
